### ISSUE TITLE
create template for the data for nicolas and yvonne to work with

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/swiss-sculptures#6]
As you maybe can see, the .xlsx file, that yvonne provided is not really usable by you for several reasons (empty rows, multiple images, etc.)

Prepare the list you got (it's a attached) in a format you can easily transform in one step to a format you need (JSON or csv). Once I signed it off, we can send it to them so that they can work with that in the future.

[DH_Liste 29.5.24.xlsx](https://github.com/user-attachments/files/15510964/DH_Liste.29.5.24.xlsx)

**Comment by ZEDz318** [comment]
Yes that would be ideal, because as it is now, its very messy.
I think the biggest problem is having multiple images for a sculpture, so we could either ask them to:

- Choose one image per sculpture per time-period (1 for _historic_ & 1 for _today_)
Or

- Show them how they can add all the images in one cell as a list/JSON (since i think they are getting the data manually)

For the second option, i can then have some sort of feature where they can scroll (using arrows probably) through all available images.
What do you think is best for this?

**Comment by flicksolutions** [comment]
To have an image gallery is a significant feature that they wished for. It's not being dropped because it's not straightforward to include it in an Excel file.

All images in one cell is just one option. The other option would be to have one row per image (as it is now) but to duplicate the rest of the info. That way, it would still be easy to match pictures with works of art, and it would be easy for them to enter.

However, going with comma-separated values in one cell is also an option. You choose.

Please attach a list that  looks like you want it (containing the same information as the messy one)

**Comment by ZEDz318** [comment]
There is still one issue with the data that has to do with the photographers.
A sculpture can have many images, but the images themselves also have photographers that might change from one image to the other
I don't think they can do anything about it, but the image data in the GeoJSON format will have to become an object:

```
"image": {
       0 : {
           'url': ['' , ...],
           'photographer': ''
    }, ....
}
```

Then in the Popup component, it'll be easier to display image information with dynamic photographers

**Comment by flicksolutions** [comment]
As we talked about in the email, please make sure that for identifying where an image belongs in the data, please don't compare only the title but the** title + year fields**. Some works of art bear the same title.
